[package]
name = "lahar"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"
description = "Futures support for Vulkan"
readme = "README.md"

[dependencies]
ash = "0.29"
futures-preview = "0.3.0-alpha.16"
